// templates/vue/src/App.vue
<template>
  <div id="app" class="min-h-screen bg-gray-50">
    <nav class="bg-white shadow-sm border-b">
      <div class="container mx-auto px-4 py-4 flex items-center gap-6">
        <router-link 
          to="/" 
          class="flex items-center gap-2 text-gray-700 hover:text-green-600 transition-colors"
        >
          <Home :size="20" />
          Home
        </router-link>
        <router-link 
          to="/about"
          class="flex items-center gap-2 text-gray-700 hover:text-green-600 transition-colors"
        >
          <Info :size="20" />
          About
        </router-link>
      </div>
    </nav>
    <main class="container mx-auto px-4 py-8">
      <router-view/>
    </main>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { Home, Info } from 'lucide-vue-next';

export default defineComponent({
  name: 'App',
  components: {
    Home,
    Info
  }
});
</script>

<style>
.router-link-exact-active {
  @apply text-green-600;
}
</style>

// templates/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';
import { LucideAngularModule, Home, Info } from 'lucide-angular';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive, LucideAngularModule],
  templateUrl: './app.component.html'
})
export class AppComponent {
  title = 'Angular Starter Template';
}
<div class="min-h-screen bg-gray-50 flex flex-col">
  <header class="bg-white shadow-sm border-b">
    <nav class="container mx-auto px-4 py-4">
      <ul class="flex items-center gap-6">
        <li>
          <a 
            routerLink="/" 
            routerLinkActive="text-blue-600" 
            [routerLinkActiveOptions]="{exact: true}"
            class="flex items-center gap-2 text-gray-700 hover:text-blue-600 transition-colors"
          >
            <lucide-icon name="home" [size]="20"></lucide-icon>
            Home
          </a>
        </li>
        <li>
          <a 
            routerLink="/about" 
            routerLinkActive="text-blue-600"
            class="flex items-center gap-2 text-gray-700 hover:text-blue-600 transition-colors"
          >
            <lucide-icon name="info" [size]="20"></lucide-icon>
            About
          </a>
        </li>
      </ul>
    </nav>
  </header>
  
  <main class="flex-1 container mx-auto px-4 py-8">
    <router-outlet></router-outlet>
  </main>
  
  <footer class="bg-gray-100 border-t py-4">
    <p class="text-center text-gray-600">&copy; 2024 Angular Starter Template</p>
  </footer>
</div>
